sudo:
  false

language:
  php

php:
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - if [[ "5.6" == "${TRAVIS_PHP_VERSION}" ]]; then vendor/bin/phpcs --standard=PSR2 library; fi
  - if [[ "5.6" == "${TRAVIS_PHP_VERSION}" ]]; then vendor/bin/phpmd library text cleancode,codesize,controversial,design,naming,unusedcode; fi
  - vendor/bin/phpunit

notifications:
  email: false
